### ISSUE TITLE
Provide 1.7.0 Beta 1 tag

### ISSUE THREAD

**Issue by Visne** [NinetailLabs/syncplay-server#10]

**Comment by DeadlyEmbrace** [comment]
Will attempt to get a build out for this later today

**Comment by DeadlyEmbrace** [comment]
1.7.0-Beta1 is now available on Docker Hub [here](https://hub.docker.com/layers/ninetaillabs/syncplay-server/1.7.0-Beta1/images/sha256-3c7f1d7b15fbd77ba8f87c1f855cbf612b67cffa2002b55500ca90035c40ef6c?context=explore)
Sorry for the delay, was a little busy yesterday.
