### ISSUE TITLE
Support 1.7.0 (Final)

### ISSUE THREAD

**Issue by enchained** [NinetailLabs/syncplay-server#11]
1.7.0 (Final) was recently released: https://github.com/Syncplay/syncplay/releases/tag/v1.7.0

One of the most important changes was adding room permanence option to the server. New server arguments were [introduced](https://github.com/Syncplay/syncplay/issues/526#issuecomment-1113635037):

```
--rooms-db-file [file]
Enables room persistence. Path is to where a database file should be loaded/create where room data will be written to and read from. This will enable rooms to persist without watchers and through restarts. Will not work if using --isolate-rooms.

--permanent-rooms-file [file]
Specifies a list of rooms that will still be listed even if their playlist is empty. Path is to where a text file with one room per line. This will require persistent rooms to be enabled.
```

I suppose it would also require mounting a host folder as a volume.

**Comment by azlux** [comment]
Can you support last stable version ? Or this project isn't maintained ?

**Comment by DeadlyEmbrace** [comment]
Sorry, I've been a little distracted. I'll try and get this updated to 1.7.0 this week.
